apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://cicop-prometheus:9090
    access: proxy
    isDefault: true
